// index.ts - UI tests constants barrel export

// Demo configuration constants
export {
  DEFAULT_AUDIO_DEMO_CONFIG,
  MINIMAL_AUDIO_DEMO_CONFIG,
  ADVANCED_AUDIO_DEMO_CONFIG,
  DEFAULT_DRAG_TEST_CONFIG,
  BASIC_DRAG_TEST_CONFIG,
  ADVANCED_DRAG_TEST_CONFIG,
  STANDARD_UI_INTERACTIONS,
  STANDARD_INTERACTIVE_SELECTORS,
  STANDARD_EXCLUSIONS,
  DEMO_SECTION_PRIORITIES,
  CONFIG_VALIDATION_RULES
} from './demo-configurations.constants';

// Navigation constants
export {
  UI_TEST_ROUTES,
  DEFAULT_UI_TEST_ROUTE,
  UI_TEST_PATHS,
  UI_TEST_ROUTE_IDS,
  BREADCRUMB_LABELS,
  NAVIGATION_CATEGORIES,
  ROUTE_ACCESS_LEVELS,
  ROUTE_METADATA
} from './navigation.constants';